spring.application.name=campusfound

# DATABASE CONFIGURATION
spring.datasource.url=${DB_URL}
spring.datasource.username=${DB_USERNAME}
spring.datasource.password=${DB_PASSWORD}

# JPA CONFIGURATION
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true
spring.datasource.hikari.data-source-properties.ssl=true
spring.datasource.hikari.data-source-properties.sslmode=require
spring.datasource.hikari.data-source-properties.sslfactory=org.postgresql.ssl.NonValidatingFactory
spring.datasource.hikari.connection-timeout=30000
spring.datasource.hikari.initializationFailTimeout=0



# PostgreSQL Dialect
spring.jpa.database-platform=org.hibernate.dialect.PostgreSQLDialect

#JWT
jwt.secret=${JWT_SECRET}
jwt.expiration=900000

#imagekit
imagekit.public-key=${IMAGEKIT_PUBLIC_KEY}
imagekit.private-key=${IMAGEKIT_PRIVATE_KEY}
imagekit.url-endpoint=${IMAGEKIT_URL_ENDPOINT}

brevo.api-key=${BREVO_API_KEY}
brevo.sender-email=${BREVO_SENDER_EMAIL}
brevo.sender-name=${BREVO_SENDER_NAME}